#+HTML_HEAD: <link rel="preconnect" href="https://fonts.googleapis.com" />
#+HTML_HEAD: <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
#+HTML_HEAD: <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900&family=Source+Sans+3:ital,wght@0,200..900;1,200..900&family=Source+Code+Pro:ital,wght@0,200..900;1,200..900">

#+HTML_HEAD: <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
#+HTML_HEAD: <script src="lilac.js"></script>

# Include additional CSS styles.
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="syntax-highlighting.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="lilac.css" />

#+HTML_HEAD: <!-- LILAC_HTML_HEAD -->
