# Include additional CSS styles.
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="syntax-highlighting.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="lilac.css" />
#+HTML_HEAD: <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Serif+Pro:wght@400;700&family=Source+Sans+Pro:wght@400;700&family=Source+Code+Pro">

#+HTML_HEAD: <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
#+HTML_HEAD: <script src="lilac.js"></script>
