all: test weave
.PHONY: all

test: tangle
	emacs --quick --batch --kill --load ert \
		--load lilac.el \
		--load lilac-tests.el \
		--funcall ert-run-tests-batch-and-exit
.PHONY: test

weave: README.html
.PHONY: weave

README.html: README.org
	$(call run_emacs,(lilac-gen-css-and-exit),README.org)
	$(call run_emacs,(lilac-publish),README.org)
	# Fix inline styles.
	sed -i 's/<style>.csl-left-margin{float: left; padding-right: 0em/'\
	'<style>.csl-left-margin{float: left; padding-right: 1em/' README.html
	sed -i 's/.csl-right-inline{margin: 0 0 0 1em;}<\/style>/'\
	'.csl-right-inline{margin: 0 0 0 2em;}<\/style>/' README.html
	sed -i 's|<h2>Table of Contents</h2>||' README.html
# tangled_output are all files that are generated by tangling README.org.
tangled_output = \
	citations.bib \
	lilac.css \
	lilac.el \
	lilac.js \
	lilac.theme \
	.gitattributes \
	.gitignore \
	Makefile \
	shell.nix \
	syntax-highlighting.css

tangle $(tangled_output) &: README.org
	# Generate the toplevel Makefile (this file) and others as described in
	# tangled_output. In a way this bootstraps the whole literate-programming
	# pipeline.
	$(call run_emacs,(org-babel-tangle),README.org)
	touch tangle
define run_emacs
	emacs $(2) --quick --batch --kill --load $(PROJ_ROOT)/lilac.el --eval="$(1)"
endef

PROJ_ROOT := $(shell git rev-parse --show-toplevel)
update-deps: package/nix/sources.json package/nix/sources.nix
	cd package && niv update
	touch update-deps
